### ISSUE TITLE
“Download”下载按钮不见

### ISSUE THREAD

**Issue by J1npen** [oe/download-git-userscript#12]
## 问题
在进入任意库中的任意一个文件夹或文件后，本应出现在右上角的“Download”选项没有出现

## 预期结果
应该会出现的“Download”选项

## 我的系统
脚本版本:
0.7.1
Chrome版本：
129.0.6668.59（正式版本）
操作系统：
Windows 11 家庭中文版, 23H2

**Comment by oe** [comment]
This issue is caused by the deprecated event `DOMSubtreeModified`, which has been fixed just now. Please upgrade to the latest version.

[install script via greasyfork](https://greasyfork.org/scripts/411834-download-github-repo-sub-folder/code/Download%20github%20repo%20sub-folder.user.js), [greasyfork home page](https://greasyfork.org/scripts/411834-download-github-repo-sub-folder)
[install script via openuserjs](https://openuserjs.org/install/oe/Download_github_repo_online.user.js), [openuserjs home page](https://openuserjs.org/scripts/oe/Download_github_repo_online)
